lexical = {'first_person_singular': ['yo', 'mio', 'mi'], 'second_person_singular': ['tú', 'tu', 'tuyo', 'usted', 'vos'],
           'third_person_singular': ['él', 'el', 'ella', 'ese', 'esa', 'aquel'],
           'first_person_plurar': ['nosotros', 'nuestros'],
           'second_person_plurar': ['tuyos', 'tuyas', 'ustedes', 'vosotros', 'vosotras'],
           'third_person_plurar': ['ellos', 'ellas', 'ese', 'esos', 'aquellas', 'aquellos'],
           'adverb_time': ['ya', 'aún', 'hoy', 'tarde', 'pronto', 'todavía', 'ayer', 'recién', 'nunca', 'siempre',
                           'jamás', 'ahora'],
           'adverb_neg': ['ya', 'aún', 'hoy', 'tarde', 'pronto', 'todavía', 'ayer', 'recién', 'nunca', 'siempre',
                          'jamás', 'ahora'],
           'adverb_place': ['ahí', 'allí', 'aquí', 'acá', 'delante', 'detrás', 'arriba', 'abajo', 'cerca', 'lejos',
                            'encima', 'fuera', 'dentro'],
           'adverb_mode': ['mal', 'bien', 'regular', 'despacio', 'así', 'mejor', 'peor', 'claro', 'similar',
                           'fácilmente'],
           'adverb_cant': ['muy', 'más', 'poco', 'bastante', 'bastante', 'menos', 'mucho', 'algo', 'casi'],
           'adjetives_neg': ['aburrido', 'ácido', 'amargo', 'ancho', 'atrevido', 'bajo', 'blando', 'caliente', 'común',
                             'conocido', 'corto', 'débil', 'delgado', 'diferente', 'difícil', 'duro', 'enfermo',
                             'estrecho', 'falso', 'feo', 'frío', 'húmedo', 'imposible', 'izquierdo', 'lento', 'malo',
                             'menor', 'muerto', 'negro', 'peor', 'pequeño', 'pobre', 'poco', 'popular', 'raro', 'rojo',
                             'salado', 'simple', 'sinvergüenza', 'solo', 'soso', 'tímido', 'tonto', 'triste', 'viejo'],
           'adjetives_pos': ['alegre', 'alto', 'azul', 'blanco', 'bonito', 'buen', 'bueno', 'caliente', 'capaz',
                             'central', 'contento', 'derecho', 'diferente', 'divertido', 'dulce', 'duro', 'exterior',
                             'famoso', 'final', 'fresco', 'fuerte', 'gran', 'grande', 'guapo', 'guay', 'igual',
                             'imposible', 'interesante', 'joven', 'largo', 'listo', 'mayor', 'mejor', 'mucho',
                             'musical',
                             'nacional', 'natural', 'nuevo', 'perfecto', 'popular', 'posible', 'primer', 'primero',
                             'principal', 'próximo', 'rápido', 'real', 'recto', 'rico', 'salado', 'sano', 'seco',
                             'útil',
                             'verdadero', 'verde', 'vivo'],
           'who_general': ['familia', 'familiar', 'familiares', 'acompañante', 'aprendices', 'aprendiz', 'artista',
                           'asistente', 'compinche', 'directiva', 'directivo', 'especialista', 'estudiante',
                           'estudiantes', 'joven', 'jovenes', 'lider', 'pareja', 'projimo'],
           'who_male': ['abuelo', 'alcalde', 'medico', 'alumno', 'alumnos', 'amigo', 'amigos', 'asesor', 'chiquillo',
                        'compa', 'compadre', 'compañero', 'compañeros', 'decano', 'director', 'doctor', 'empleado',
                        'empresario', 'entrenador', 'esposo', 'esposito', 'experto', 'expertos', 'funcionario',
                        'hermano', 'ingeniero', 'investigador', 'jefe', 'jugador', 'padre', 'marido', 'medico',
                        'muchacho', 'muchachos', 'niño', 'niños', 'novio', 'hijo', 'primo', 'papa', 'pequeños',
                        'profesor', 'pequeño', 'secretario', 'socio', 'tutor', 'papi', 'tio', 'nieto'],
           'who_female': ['alumna', 'alumnas', 'amiga', 'amigas', 'asesora', 'chiquilla', 'comadre', 'compañera',
                          'compañeras', 'dama', 'decana', 'directora', 'doctora', 'empleada', 'empresaria', 'esposa',
                          'esposita', 'experta', 'expertas', 'funcionaria', 'hermana', 'ingeniera', 'investigadora',
                          'jefa', 'jugadora', 'madre', 'mama', 'medica', 'muchacha', 'muchachas', 'mujer', 'niñas',
                          'novia', 'novicia', 'hija', 'prima', 'pequeña', 'pequeñas', 'profesora', 'secretaria',
                          'señora', 'socia', 'tutora', 'mami', 'tia', 'nieta']}
